version: '3.7'

services:
  temperature-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: temperature-app
    ports:
      - "8080:8080"
    networks:
      - temperature
networks:
  temperature:
