version: '3.7'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: go-app
    ports:
      - "8080:8080"
    networks:
      - temperature
    depends_on:
      redis:
        condition: service_healthy
networks:
  temperature:
